version: "3" 
services:
  # Application service layer
  nginx:
    image: nginx:1.13
    volumes:
      - "./app:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - sql
  sql:
    build:
      context: ./sql
    volumes:
      - "./sql/crow/src:/crow"
      - "./sql/crow/:/app"
    ports:
      - "800:9000"
    depends_on:
      - bd5
    links:
      - bd5
    restart: on-failure
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=123.456
 
  # Data persistence service layer
  bd5:
    image: mysql:5.6
    volumes:
      - "bd_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123.456
      - MYSQL_DATABASE=teste

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - bd5
    ports:
      - 801:80
    environment:
      - PMA_HOST=bd5

  theia:
    image: theiaide/theia
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/project

volumes:
  bd_data:

